### ISSUE TITLE
documentation request

### ISSUE THREAD

**Issue by tvmaly** [plimble/ace#10]
could you show an example of using a simple template with html/template with ace ?

**Comment by zier** [comment]
https://github.com/plimble/ace-contrib/tree/master/pongo2

**Comment by zier** [comment]
this is example if you want to use html/template

`
type HtmlTemplate struct{}

func (ht *HtmlTemplate) Render(w http.ResponseWriter, name string, data interface{}) {
	err := templates.ExecuteTemplate(w, name, data)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
	}
}

func main() {
	a := ace.New()

	render := HtmlTemplate{}
	a.HtmlTemplate(render)
	a.GET("/", homePage)

	a.Run(":5000")
}

func homePage(c *ace.C) {
	c.HTML("index.html", map[string]interface{}{"name": "john"})
}
`

**Comment by zier** [comment]
`
type HtmlTemplate struct{}

func (ht *HtmlTemplate) Render(w http.ResponseWriter, name string, data interface{}) {
	err := templates.ExecuteTemplate(w, name, data)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
	}
}
`


`
a := ace.New()
render := HtmlTemplate{}
a.HtmlTemplate(render)
`

**Comment by zier** [comment]
html/template example

```
type HtmlTemplate struct{}

func (ht *HtmlTemplate) Render(w http.ResponseWriter, name string, data interface{}) {
	err := templates.ExecuteTemplate(w, name, data)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
	}
}

func main() {
	a := ace.New()

	render := HtmlTemplate{}
	a.HtmlTemplate(render)
	a.GET("/", homePage)

	a.Run(":5000")
}

func homePage(c *ace.C) {
	c.HTML("index.html", map[string]interface{}{"name": "john"})
}
```

**Comment by tvmaly** [comment]
Thanks, that is exactly what I needed.

Best regards,

Ty
