### ISSUE TITLE
c.HTML()

### ISSUE THREAD

**Issue by martinlindhe** [plimble/ace#12]
According to https://github.com/plimble/ace#html, 
this could be used `c.HTML("index.html")`

but the function definition at https://github.com/plimble/ace/blob/master/context.go#L88 takes a name and a interface.

(basically, i am looking for a way to return a single static file on a specific path)

**Comment by plirr** [comment]
name is just the file name and you can send nil as the interface if necessary.
c.HTML("index.html", nil)

**Comment by martinlindhe** [comment]
I seem to have forgotten to respond to this

Thanks @plirr, Static() was what I ended up using!
