### ISSUE TITLE
Could you add a LICENSE file?

### ISSUE THREAD

**Issue by hnakamur** [plimble/ace#3]
First of all, thanks for creating and sharing a nice software!

Could you add a LICENSE file?
[Open source licensing - User Documentation]( https://help.github.com/articles/open-source-licensing/ ) might help for choosing a license.

Thanks!

**Comment by witooh** [comment]
resolved cae91fc7e2b14dbbbfecbd7da883d77ecd9027fa

**Comment by hnakamur** [comment]
Thanks for a prompt response!
