### ISSUE TITLE
nested router and static path

### ISSUE THREAD

**Issue by rhacker** [plimble/ace#6]
I have a problem regarding using nested router and static path. I have a simple

```
a.Static("/public", "./public")
a.GET("/signin", func(c *ace.C) {/*stuff here */})
a.GET("/one/another", func(c *ace.C){/*stuff here */})
```

I have a simple css declaring in the template file like this 
```
<link rel="stylesheet" href="public/dist/main.css"/>  
```

With the first route, it requests the path correctly which is `public/dist/main.css`
but in the second route, it requests `one/public/dist/main.css` which is not available.

**Comment by witooh** [comment]
Because you use relative path in href. Change it to absolute path
```html
<link rel="stylesheet" href="/public/dist/main.css"/>  
```

**Comment by rhacker** [comment]
thanks for your answer, it's not the problem of the path nor the framework. It's the problem on the reactjs router I'm working on. 
Thanks for your participation :)
