### ISSUE TITLE
Need some additional help how to use ace-contrib/pongo2

### ISSUE THREAD

**Issue by robvdl** [plimble/ace#8]
I am sorry that this isn't really a bug, but I can't quite figure out how to correctly use ace-contrib/pongo2 with ace.

It mentions in the README that this implements the Renderer interface, but there isn't really an example, so I can't seem to figure out how it's meant to be used correctly.

**Comment by zier** [comment]
i have to add document ace-contrib/pongo2

https://github.com/plimble/ace-contrib/tree/master/pongo2

**Comment by robvdl** [comment]
thanks
