### ISSUE TITLE
Static on the root URL / does not seem possible

### ISSUE THREAD

**Issue by robvdl** [plimble/ace#9]
The following doesn't seem to be possible:

a.Static("/", "public")

The reason I am mentioning this, is because a lot of other Go frameworks seem to use the root URL for static files.

This works fine however:

a.Static("/static", "public")

It's not a huge deal, but would be nice if this can be made possible without too much hassle.

**Comment by witooh** [comment]
Fixed

**Comment by robvdl** [comment]
I just tried this and it doesn't seem to like it with other URL's

panic: wildcard route conflicts with existing children

it works on it's own though, if that was the only URL

**Comment by witooh** [comment]
Yes this is the limitation. Httprouter use tree structure for routing.
If you use static is the root path, all routes are point to static. 
You cannot add another url.
The best way for static, you should route static in some sub route e.g., /public to avoid route conflict
